
###
GET http://localhost:3000/stocks HTTP/1.1

###
GET http://localhost:3000/stocks/67a4c676acce56c2b66f3bf8 HTTP/1.1

###
GET http://localhost:3000/stocks/Apple HTTP/1.1

// RESET TESTS ------------------------------------------------

###

PUT http://localhost:3000/stocks/67a4c71cacce56c2b66f3bfd  HTTP/1.1
content-type: application/json

{
    "title": "Amazon",
    "price": 300.00,
    "sym": "AMZN"
}

###

PUT http://localhost:3000/stocks/67a4c739acce56c2b66f3c05  HTTP/1.1
content-type: application/json

{
    "title": "NVIDIA",
    "price": 180.00,
    "sym": "NVDA"
}

###

PUT http://localhost:3000/stocks/67a4c725acce56c2b66f3c01  HTTP/1.1
content-type: application/json

{
    "title": "Tesla",
    "price": 350.00,
    "sym": "TSLA"
}

###

PUT http://localhost:3000/stocks/67a4c721acce56c2b66f3bff  HTTP/1.1
content-type: application/json

{
    "title": "Apple",
    "price": 250.00,
    "sym": "AAPL"
}

// TESTS ------------------------------------------------

###

PUT http://localhost:3000/stocks/67a4c71cacce56c2b66f3bfd  HTTP/1.1
content-type: application/json

{
    "title": "Amazon",
    "price": 200.00,
    "sym": "AMZN"
}

###

PUT http://localhost:3000/stocks/67a4c739acce56c2b66f3c05  HTTP/1.1
content-type: application/json

{
    "title": "NVIDIA",
    "price": 201.00,
    "sym": "NVDA"
}

###

PUT http://localhost:3000/stocks/67a4c725acce56c2b66f3c01  HTTP/1.1
content-type: application/json

{
    "title": "Tesla",
    "price": 401.00,
    "sym": "TSLA"
}

###

PUT http://localhost:3000/stocks/67a4c721acce56c2b66f3bff  HTTP/1.1
content-type: application/json

{
    "title": "Apple",
    "price": 190.00,
    "sym": "AAPL"
}

// END OF TESTS ------------------------------------------------

###
DELETE http://localhost:3000/stocks/67a4c676acce56c2b66f3bf8 HTTP/1.1
