###
POST http://localhost:3075/new_funds HTTP/1.1
content-type: application/json

{
    "userName": "TestUser123",
    "funds": 500.00
}

###
GET http://localhost:3075/funds/TestUser123 HTTP/1.1

###
PUT http://localhost:3075/funds/TestUser123  HTTP/1.1
content-type: application/json

{
    "funds": 10000.00
}

###
DELETE http://localhost:3075/funds/TestUser123  HTTP/1.1

###
POST http://localhost:3025/new_order HTTP/1.1
content-type: application/json

{
    "userName": "TestUser123",
    "orderType": "buy-limit",
    "stock_title": "Amazon",
    "strike_price": 200.00,
    "quantity": 2,
    "executed": false
}

###
POST http://localhost:3025/new_order HTTP/1.1
content-type: application/json

{
    "userName": "TestUser123",
    "orderType": "buy-stop",
    "stock_title": "NVIDIA",
    "strike_price": 200.00,
    "quantity": 1,
    "executed": false
}

###
POST http://localhost:3025/new_order HTTP/1.1
content-type: application/json

{
    "userName": "TestUser123",
    "orderType": "sell-limit",
    "stock_title": "Tesla",
    "strike_price": 400.00,
    "quantity": 1,
    "executed": false
}

###
POST http://localhost:3025/new_order HTTP/1.1
content-type: application/json

{
    "userName": "TestUser123",
    "orderType": "sell-stop",
    "stock_title": "Apple",
    "strike_price": 200.00,
    "quantity": 1,
    "executed": false
}

###
GET http://localhost:3025/orders/TestUser123 HTTP/1.1
Content-Type: application/json

{
    "orderType": "Buy"
}

###
PUT http://localhost:3025/orders/TestUser123/Amazon  HTTP/1.1
content-type: application/json

{
    "orderType": "Buy",
    "strike_price": 200.00
}

###
DELETE http://localhost:3025/orders/TestUser123/Amazon  HTTP/1.1
content-type: application/json

{
    "orderType": "Buy"
}

###
POST http://localhost:3050/purchase HTTP/1.1
content-type: application/json

{
    "userName": "TestUser123",
    "stock_title": "Amazon",
    "stock_sym": "AMZN",
    "amountOwned": 5
}

###
POST http://localhost:3050/purchase HTTP/1.1
content-type: application/json

{
    "userName": "TestUser123",
    "stock_title": "NVIDIA",
    "stock_sym" : "NVDA",
    "amountOwned": 5
}


###
POST http://localhost:3050/purchase HTTP/1.1
content-type: application/json

{
    "userName": "TestUser123",
    "stock_title": "Tesla",
    "stock_sym": "TSLA",
    "amountOwned": 5
}

###
POST http://localhost:3050/purchase HTTP/1.1
content-type: application/json

{
    "userName": "TestUser123",
    "stock_title": "Apple",
    "stock_sym": "AAPL",
    "amountOwned": 5
}

###
GET http://localhost:3050/user/TestUser123 HTTP/1.1

###
GET http://localhost:3050/user/TestUser123/Tesla HTTP/1.1

###
GET http://localhost:3050/user/TestUser124 HTTP/1.1

###
PUT http://localhost:3050/user/TestUser123/NVIDIA  HTTP/1.1
content-type: application/json

{
    "amountOwned": 5
}

###
PUT http://localhost:3050/user/TestUser123/Amazon  HTTP/1.1
content-type: application/json

{
    "amountOwned": 10
}

###
DELETE http://localhost:3050/user/TestUser123/NVDA  HTTP/1.1

###
DELETE http://localhost:3050/user/TestUser123/TSLA  HTTP/1.1