###
POST http://localhost:3075/new_funds HTTP/1.1
content-type: application/json

{
    "userName": "TestUser123",
    "funds": 500.00
}

###
GET http://localhost:3075/funds/TestUser123 HTTP/1.1

###
PUT http://localhost:3075/funds/TestUser123  HTTP/1.1
content-type: application/json

{
    "funds": 10000.00
}

###
DELETE http://localhost:3075/funds/TestUser123  HTTP/1.1
